name: Build/Release Screenshot Plugin

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for the release'
        required: true

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    name: Build and Upload Assets
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js with Corepack (Yarn)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Enable Corepack and install dependencies with Yarn
        run: |
          corepack enable
          YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install

      - name: Run build script
        run: node build.mjs

      - name: Check if dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found after build"
            exit 1
          fi
          echo "Build artifacts found in dist directory"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          tag_name: ${{ github.event.release.tag_name || inputs.tag }}
          fail_on_unmatched_files: false
          update_existing: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
